paths:
  "/products":
    post:
      tags:
        - inventory.products
      summary: Crear un nuevo producto
      description: |
        Se crea un nuevo producto teniendo como parámetros las categorias 
        de familia, subfamilia, elemento y modelo.

        El servicio puede crear automaticamente estas categorias en caso no existan
        pero debe tenerse en cuenta las siguientes condiciones.
        - Para indicar que una categoria ya existe debe proporcionarse su Id. En caso no se 
        proporcione el Id, se considera que la categoría es nueva y se verificará que el nombre
        no exista en la DB.
        - En caso se proporcione el Id, el nombre enviado debe coincidir con el nombre de la 
        categoría existente.
        - Debe respetarse la jerarquía al momento de crear las categorías. El orden de creación
        es de arriba hacia abajo.
      operationId: addProduct
      responses:
        "201":
          description: Product created
        "400":
          description: Bad request
      requestBody:
        $ref: "#/components/requestBodies/Product"
    get:
      tags:
        - inventory.products
      summary: Listado de productos del inventario
      description: |
        Listar todos los productos del inventario. Existen filtros opcionales:
        - stock: Toma los valores 'yes': productos con stock disponible o 'all': todos los productos.
        - familyId, subfamilyId, elementId, modelId : Categorias de productos
        - code: Codigo de producto

      parameters:
        - $ref: "#/components/parameters/stock"
        - $ref: "#/components/parameters/code"
        - $ref: "#/components/parameters/familyId"
        - $ref: "#/components/parameters/subfamilyId"
        - $ref: "#/components/parameters/elementId"
        - $ref: "#/components/parameters/modelId"
        - $ref: "#/components/parameters/providerId"
        - $ref: "#/components/parameters/pagePagination"
        - $ref: "#/components/parameters/pageSizePagination"
      operationId: listProducts
      responses:
        "200":
          description: Products found
  "/products/{id}":
    get:
      tags:
        - inventory.products
      summary: Encontrar producto por Id incluyendo stock
      operationId: getProductById
      parameters:
        - $ref: "#/components/parameters/paramId"
        - $ref: "#/components/parameters/noStock"
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid ID supplied
        "404":
          description: Resource not found
components:
  parameters:
    noStock:
      name: noStock
      in: query
      description: Flag para traer producto sin stock
      required: false
      schema:
        type: bool
    stock:
      name: stock
      in: query
      description: Indicador de si incluir productos con stock o todos
      required: false
      schema:
        type: string
        enum: ["yes", "no", "all"]
    code:
      name: code
      in: query
      description: Código único de producto
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
    familyId:
      name: familyId
      in: query
      description: Id de la familia del producto
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
    subfamilyId:
      name: subfamilyId
      in: query
      description: Id de la subfamilia del producto
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
    elementId:
      name: elementId
      in: query
      description: Id del elemento del producto
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
    modelId:
      name: modelId
      in: query
      description: Id del modelo del producto
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1

  requestBodies:
    Product:
      content:
        application/json:
          schema:
            type: object
            properties:
              familyId:
                type: string
                description: Id de la familia al que pertenece. Opcional para indicar que la familia existe.
              subfamilyId:
                type: string
                description: Id de la subfamilia al que pertenece. Opcional para indicar que la subfamilia existe.
              elementId:
                type: string
                description: Id del elemento al que pertenece. Opcional para indicar que el elemento existe.
              modelId:
                type: string
                description: Id del modelo al que pertenece. Opcional para indicar que el modelo existe.
              providerId:
                type: string
                description: Id del proveedor del producto
              familyCode:
                type: string
                description: Codigo de la familia al que pertenece.
              subfamilyCode:
                type: string
                description: Codigo de la subfamilia al que pertenece.
              elementCode:
                type: string
                description: Codigo del elemento al que pertenece.
              familyName:
                type: string
                description: Nombre de la familia al que pertenece.
              subfamilyName:
                type: string
                description: Nombre de la subfamilia al que pertenece.
              elementName:
                type: string
                description: Nombre del elemento al que pertenece.
              modelName:
                type: string
                description: Nombre del modelo al que pertenece.
              compatibility:
                type: string
                description: Marcas con los que es compatible el producto
              tradename:
                type: string
                description: Nombre comercial del producto
              suggestedPrice:
                type: integer
                format: int32
                description: Precio sugerido. El valor debe tener una precision de 2 decimales
              imageBase64:
                type: integer
                format: int32
                description: |
                  Imagen codificada en Base64. El tamaño no debería exceder de 20MB.

                  Para codificar https://www.base64encode.org/

                  Para decodificar https://codebeautify.org/base64-to-image-converter
            required:
              - familyName
              - subfamilyName
              - elementName
              - familyCode
              - subfamilyCode
              - elementCode
              - modelName
              - providerId
              - compatibility
              - tradename
              - suggestedPrice
          examples:
            Todo Nuevo:
              value:
                familyName: "Familia 1"
                subfamilyName: "Subfamilia 1"
                elementName: "Elemento 1"
                modelName: "Modelo 1"
                familyCode: "F1"
                subfamilyCode: "SF1"
                elementCode: "El1"
                providerId: 1
                compatibility: "Compatible con todos"
                tradename: "Nombre comercial"
                suggestedPrice: 10000
            Con imagen:
              value:
                familyName: "Familia 1"
                subfamilyName: "Subfamilia 1"
                elementName: "Elemento 1"
                modelName: "Modelo 1"
                familyCode: "F1"
                subfamilyCode: "SF1"
                elementCode: "El1"
                providerId: 1
                compatibility: "Compatible con todos"
                tradename: "Nombre comercial"
                suggestedPrice: 10000
                imageBase64: /9j/4AAQSkZJRgABAQEAeAB4AAD/4QAiRXhpZgAATU0AKgAAAAgAAQESAAMAAAABAAEAAAAAAAD/2wBDAAIBAQIBAQICAgICAgICAwUDAwMDAwYEBAMFBwYHBwcGBwcICQsJCAgKCAcHCg0KCgsMDAwMBwkODw0MDgsMDAz/2wBDAQICAgMDAwYDAwYMCAcIDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAz/wAARCABwAMgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9/KKKKACiiigAooooAKKKKACiuO8cfHfwp8Nria31rX9Ls7y3RZZbQTCS5VGztYxrllBwcEjHvXkHhL/gqv8ABfxRpvmSeLBpd2tw1s9ndWrvJGwJALPCJIgrYyG34AzkgggGouZdT6HvNXt9Os5Li4kjt4IU8ySSVgiRj1ZicD65xXi3jH/gpJ8F/BHiRdLuvGlvdThiksmn2k99DbkDOGkhRl/75Jx1OBzX5Y/8Frv+Ct3gHX/Es2meE7rxp4ovrW2SG1skli0vSi24iSZEuIjcThsqDIscajyhsnYErX5t6Z/wUQ+IumXkclnDYzaao2raXztd5A7GU4l65PBx09M0DP6aPiT/AMFLPg38OtEjvpPF0Oro0fnlNLhe6MceB80hAwgG4cMQ3I4615noH/Bdb9nnWpbtl8Ra7FYWEDSS6k+jyyWJkGMQLNHuSSRs8eWWUYIZlPFfht4H/bP8N/tD3djoXjbR9L8L6hLIIrS7vhHfWKynhXSWWMrEx7CUAZPLE4Fer/Ef/gnD8RjfWb+G/C+n/EjUtSO+bVfGWvqlto4TaVUWpUKylSWyiOcqowBjAB+pz/8ABez4Yz69Ha2XhHx5qFvJII0uEtYUUbsFS26TbHlSDtkdXyQNvIr6e+Av7V/hX9oGa8tdGkvodT09FkurK5WMywKcdTEzp3HG7d7dcfk18AP+CZGuQXF1q3xY8cL421fUCj/ZrSzW2tdLkGWxBK2ZSTvwXAjJPPA4q74ctND/AGT/AAi9tceC/HC3VvrjxW9vqF7JefarnAcO1xuK5dCVAhVsquME7qAP2kWVXZlB5Xg+1Or5X/Z9/bT8Wan4f0OLxn4LuNFhkjY3Wo3+oIL6XJO0x2caOW54OXUhQGxzgfU0bEg525z27UAOooooAKKKKACiiigAooooAKKKKACiiigAooooAR32Lmvlr/gpB8etU+Hljo/h/Sbq8s/7Sie91CTT9UFnefZlljiIUqDLGpMgO9MElcAthlr6iuX2QluMLgnJ4HvX4V/8FN/Fniz9q/4vaZ8WPhe39sax4T8TPDp9vb3SQxzWiSRwSQOzlRtDWw8xSfl8124xQBxH7Qn7THh/QYLyx8N+F9MSzvre5k1rxDqwea2sbTA81piMS3Duw2IOWZwDgZFfNV18bdYg8C6DqEvi7/hH9JuoJJra4m062u9d1SIP5abLZVIiVm+RS6tI235TJ99vr79pn9kfTPiF4GGl6DoGv61peqaml94ptkvreJrmGG5EsFraqwG1CQWkLNvY7NuMYr5efwD8RPB/xZ/tL4cacupfH7x5rF4w1C8RdP03wFpkQWIiJ7geTG3lByZSAI440VAz53ceJp1JPmg7HdhatBe7WV/zO/0Zk8ZeFvtXx60vQ/hjoN88b6PY+K9TgkvrtWBDO1siiW2XgYZ9jc/dAAY5P7Vf/BHXxF8MPBE/jbwC03iLwzbwfa9QsIybi6sYCocTxFSzXMIjO5tuWCkN8y7mTgvBHxs/Z5+EvjyaSbwTc/thftFSXEa6f/aNxdnwtptyvysLa2UPNqkg+XduDBigZPL5A/Vn9gb4tfHv4c6JrnjX9trWfhJ8HdD8RTxJ4N0ue5tNGv4yPvqsSy4Eaq6sVld5kwd21QANKNdy92orSXTsGKwip+/SlzRez7n4Rnw7a6lp4ZvLlhuFIx/rEI9FZcryOmSf93hhX3N/wSh/4KWN+zt4i0v4W/FLUt3w5v5I7fRNeun3y+GJMnZBM5BY2jMwVS2PJ46R52ewf8FrP+CUv/CjdU1L4wfD3TVi8IzSmTxXo9siquhSuy4vITuLfZpncF1AAiclgfKJ8j83dS0eG5sJIZ2V4JlKvlCoI6cKwLFuvUAgk/h0HCftJ/wVL0r9qrTPDHhzS/2YtJ8OtNqTT2/iHVbm7sYNT0fHkmJ4Pt8qW6xkNJudVlcYBULgONL9i3x7pPwh0a1+G/jbx/4b8RfGpZhd+KtN0G6l1L+yLiVm+WWYqrxnaAEEoaQbMEnaXr5j/wCCJH/BUS70TVbP9nX4rahc2eoaW0dj4K1a6Uxsync0em3MjYIfb/qXLZyPJbAMOfrx/wDglt8KPD37SXij4uaLoOqWfjbxUjLqECa/e2ek3sjNuklkgjOS0jKGZSroWQt5YZmZgDrtW/Z38Nma5ufHGpah4yO8zLBfzfZ9LiXcxDNbRMFm7DNwZcEcbeSO7/Zq/bj8M6p4yuvC3h211LxNY24O6fSbPzLDS3VSRG05AiXdt2qgctnBAI5ryjxX8N/hXqWo6g/izUpPiPJ4ZkEMmhweZZ6Bps6hdymNdyySAAlo5pLnYVVvKjLKW/FjXv8Agul8bP2svGV5qN5qafDP4cfC/T5vEtr4L8DsNLe/8uWCGC2e4IYsqyyrI+5GjAEmYWztAB/VL4V1r/hItKju/s9xaq5YKk6hXIBxnA7VqV8X/wDBDj/gpvJ/wVC/ZCg8V6hpqaX4i0CdtL1mFLpZgZg8mw4wrrmJUbJUBt/ByGVftCgAooooAKKKKACiiigAooooAKKKKACud+KGtan4d8E6pe6LpraxrFvbM9lZZ2LdS/woz4O1S23J6hQSORXRV4f+1t4N1yfxZ4J8ZeH49WvrrwZPerNZadKFuJI7q1KLIqEEShJo4dyFW+R5GAJQAtRvoTJ2Vz5F+L3iz4+ePfiXN4T+Iutx+H7O/iafT7HSx9lsb+FQplQFTvmO1h8sjnIDjapVwv52+APjbH+y/wCHvGmvapZR6lD4i8fzpc2Gnny7W0RbZHmv7WVcmSOe1W2uguF2STTLuUq9fRf7Snxb/aE0j4veGZvizoN7b6tZXEWo6fdOtvGpWa5t4zAiwttKrbtMv3d0e+ZmIZpMfGXxpkm8MeDzp9vJdeFpNF8c61JHbTwF7PRTciK6heJsnda3Bka46P5ZuZIypEW2nKNtAjK6ML4yaT4ut/gfqFn/AMJLfy+IP2ctc8yx1y2uG+1az4b1aOOWG83gkySAIu9+SR5ucFc16j+zz+2Npvxg8P8Ag74f/G2wHiCbxZoA8vxKm2O4My3FxbukoXYNzrCpV0Iycq2CxkrwXSf+CnWo/wDClrz4d6X4f0S603V7CC11O0v7o7Z44lmHlw4+dE8uZ4whcuFCAkhCWZ8N/jl4b+Od7qTaxpA0zxlb6e8ekr9oNnDC7lwkZQHY0RaVRvxwSMqmVZs7Pmvc0TXLy217n1f8RPgT8ZP2aPF+gfD/APZv1D4R/DfQ7uzOpW/xIkmg0/UvE9mxHmq95e+a6zxMwVlUEqW48vBUeX+EP2e/2VfBHj+++IX7Wn7TzfFTxtp8kUv9i+FJbjVtRvpYyNnmaikj4BKqcSGFMH74y1bvwh8Yaj8U/wBlHxT8EPHlmmuweHNVtptOvTOxbSboZbzIZFA8zdEFDqW4G0kqzPnufgH4T+C/7PPxw8J6J8FfgxpvjL45+IL6ynkspo7vU5LGxy0dxveUtFp3lgCaO5VPM2vFkHDCsalL2kk1ujqw+J9lGUJfC90t36Pofpp/wTC/ao0f9rr9mfT/AAxeaLJ4f8S+GdKS1i0fVY/Ln1fRdvlW1y8DMxw8WxJotziKRiuSjxl/zf8A28v+Cfdj+yV+0rqNn4N0HWrXwVfWg1azlnuYtNs7OLkSxy6xLI7RxROCAsSRybSoYsMSP+oGo+NfAvgzVNK1iPT7jxV480uR2t45h9nOizsrK6NKu5slGKsFZhIhGflIz4Z+05+1TqWu6VqOpLceHtc8caGPt/hi1vPD66rbaZfLwHjgyB5wUsEcsXDMG+faEroON7n5ga7/AMEdPH3xz1W38eQap4J+GfwqsbYzap408TCXSNDtoz/BZrcE3N4zAAiXAR224kDjC/oR/wAE5v8Ago1o3x4/Ze/4m3jTUPF+s+D759DudUgsvst/4lRctb3jbsrH5kOA3LMxUsTljXwn+0doWvftv+HNS174q+KrrxLbzK4fxLr1/DDpelc9YDgW0ewgLizhZXIySrcjif8AgjJqF18P9Z+KHgu+mmaWzWxuYneN4lmSM3S+YquAdrJLBg+g6nrQB+xWnXdv8ZPAF5q1jZfYllvXs5IGuZLhcLHEVOXPBYbwcYycV/Or+0X8Nbb9iL/gpH4n8P620lh4c1C8mWaaWHcqabqdu8cr+Xht/lGV3UEEE26/h/RN+xjoGrf8ID4ka60+4tbHUJre40yaeMxx3BVGBZARuK/KgyF5ySM9vkP9t39hTxx+3/4vuNS+IHg3wf8ABfwb4SjZLzxXr+oWWoXl5a5BADQyFI4wyggeYhYsB5iklGAKP/Bol8APiR8B/Hfxit/EFjqFn4QmtrNraTzx5F7crJLGs21SyurwhTGysVI3EFga/cyNty/TivzM/wCCNv8AwTp+DfgzQ9U1rwL4Z8VX/hcwwCy8a64v2O18VOWkMh0+wBQQQR4Gbj7PGZTKAkkoQsP0xtIVt7dY0/1aAKvzbuB05oAkooooAKKKKACiiigAooooAKKKKACiiigD8I/+C/v/AAVv8Raz+0fq/wAFfh/Dpml6d8NZlTVtdktY7m6vNReCORooC6nyYohKqPtAeRwwyqou78y/FfwH+Mn7ZOk6xrkN1r3jW8sYZ9budJtY/wDR7yGCNDdSWsUexfNijCtLGq+Y6ncu5iQfev8Ags38Mbj4Tf8ABV/46abJGzR6pr0PiC2ccfaItQsbe4B7/dlaaPtkxH1Ged/Zq/ad8SfsjWVzfeB/ETWdt4ygjW7DQBbnw5qtozm1vEOcAgSyBZRsE0FxdW7qfLcikrktnxnYeGI4rSG6mkGC29WSQqDhQwYFPXdG25M4RxKq/JJE3czfHKHT/CGi2ljp9vHrXhS4F1YXrQhd3zDdC6g7vLkAIePewV/PWMiIxKlv9q74HeK/Aut6T4o1LQZvDOifEKW+m0yEgfZ7e8tbs22o2g24Cm3vZmLABdguHC8HnxX7WqFZIwyquGUtn5gQp5+mYgf9oH3qQ3Ptbw58bPEHwq8CXWtaXq9m2ijVlSPQbjMs1nHKfPi8mV8GaOVCyEiNXRnViCJAx9V/Yvn+JH7If7YF34s+GvhW28SaXqNvNCba/wBTXTl1G2mCT+X57bnSSKSKJyQjn90RxvBHxX8HFh+Leg3Giz/bJb3SC17p91bQCa4uYDCdtiu51AUSb3XnC7mAU5GPe/hT+0V4o0z4G3l5petXGjat4KvoElu/sqT3DQlwI1RJEYCQOGQgq34c0dbldLH0V8a/i58fr34sal8PdI/4SDT77xdejVZLG2v7e8Dx3iCWMJfEqRExaQkzeU2eoGBXVfscT694V+Gd1oPiKO603xN4X1/UdIv4pm3XFpILl5QrNznCTKM57V8a+CfCvhH4la/q83hX9oDVtP0W+c3t3Y6pfy6bqBmlOZMwmQRGbJOZIW8t87htxgfSH7O2sfCT4J6q3w98A+OB4pkmT+1LkhGeGKTOJUScII34VDhSxBLA4GKzUm5WNp0eWClr92n3nG/Gf41Q6f8AFLVPtF9eax4o0K6lVTbSxalqNgu8gf6ROg0zRV2nGY4Z7jGN7xvVv/gkJ+0Zovhj/gr34ZfXLHRf7N+J2nTaGZPOub5ItQfcbaT7VeFpLqWSeGCAy5ZSZR90ISPCP22/GMdt+0D4jtIXa4g8+K5ijlQGKF5reJnZYivk7zIHJeVZnOfl2DFeV/BL9oLTPhf+1PoPijxBpH/CVW9nHdfbdPe9khk1IPbSRIDMSZf3ZZXxuUsI9i+XncNDE/oI/be/4LI/D39kzW7fw7pVrefE3xldCQS2OlzrDYaaqcb7q8YMoJJ+5D5jnaQQoya/M39q/wDbZ8cfHDVfDPj74nardXGgabqgmt/DVpb/AOiW3lsGMcaEbDIVUYaYs7AkAsuFH0fo/wAaf2dfjx+yf/wkHji303S9Q8CSvbaO2lxzaemoSTRJMYreBgXWIkqrmUPl1VsnJz+bn/BR3446h44v/Bc/hzQtY8O+C9Yglku4fKLaTe6upVrhIM8SSW8UsCszYbEoYKqstAH9T3/BO7xbZ+Pf2Ofh34nsv7ShtfGOjQa1Ba3r7mtRPGrmNOB8g+8PXdnjOK9uWQMO/wCIr+aP/gnF+0D8efhZ8KvD0fwX+I3jLxDrFgjM3hia+/tTSYLKOfz3hWzmR4oY3fzFMwaOXl0gAbCn+kjwJql1rfg3S7y+tbaxvry1iuLm2t7k3MNvK6KzIkpRDIqkkB9i7gM7QTip51zcqevYDWoooqgCiiigAooooAKKKKACiiigAooooA/HH/g6b/YsutW0zwb8fdEtJJF8Pw/8Iv4s2DIW2kmDafcnoFVJ5ZoWY9TdRAkBc1+NUqbojHjKyDbJkEZGPcV/YJ8RvhxoXxR8Aax4a8SabbaxoOuWktjqFnc8x3MEilXRuhGQeoIIIBBBANfze/8ABSn/AII5/Ez9gT4k3T6NoPiLxx8LryTdpHiHTrCS9ktFO3/Rb2KEPJFKu7AkKhJeoIbcq0mS0fGH7ZH7R+ufF3wq2j6/qkl81jdWWqQbzlY5Xs106duB/wAtIre3LH+JgzHLEk/OlvDceJNS8u1t2uJpD9yAeZjJY9v9oj/vk/j+mv8AwTq/4INePP8Agpb8e7jUPFei+Kvh18JdLt1S68SXVmIJ9VuI5FP2WygnCuxJ3q0+1o02sDliFr6O/a7/AOCOngv9jPw1eeGYfCa+VHFPc6HrnmO8msFY3C+bI7EbgXBaNtqox3rjG+hsEj8of2ePCN14e1rVLq+FrZJ/Z5hga6vjYpctJvTEdwBhGKszK2QMrwe1ei/BayWx+E/xMmuGupLi1sbO7awui4uLG5gvow+T/FlW+Vhg+2MMfWvin4C8QP4T8G+HdWjh/wCEZ8embTttuodNK1uPa6qHUAtHNhZVBwobzAOBg8xd/DjUfhD+y98R9W8SW8ek3OoSWHhrTzKzeZJ/pKSPnIGQsaykEdRGRuPyis2jSPL1OhsPEXwj1HxX9o+Kn7P+q3Pii1tY7my1Xw/qF3Y2etyShX8w+VDNEEmjkEm0qixtvAbJwntfwQ1rXviP8W/DOgaN8JYdL+F1pfwf2jb6dfrp7NE25DifEtzcMisXPzvgKyxqpYV5F+x3cTW/7UmneHb7U44dP02Oay1Dw9qTRyR+HdQDyedBbuzYkhmuleeIj5dtyVGHBLfRP7SH/BTK6+DfiDUvBvw38P2On63p0n2W91q/cSBJQAWESEHcqnj5/lUjGMg1Np899OX01+80coez5Xfmu3fpb0PI/wDg4s/Z5sfgT8c/hvr3hu08N2/hDxJ4dl021Ok2Elu6XVlcZmE7SSSSTbluoNksjB2COCMItfnn8KfB2qeLfEOqfZEjjaSMwSGSMScZUkD0bkYKkHnv0r3Dx94S+IP7W3xF0TV/HV14kt7HXVuHsNb1BHml1IR5yICwEWxtknzRZRADuwcIut4J8Cabobaw/htTFo/h+Nn81T81wyZSLOf78oeXpyIAP4q0MTUs/Aem+AtFjuPFV69utvb+atjHhpnVUAy3ZFAXOSR04zX6ua9/wb96/wDtg/8ABGnwd4at5NJ8C/F1vEL+PNKi1Z5zZ6Wl3DDbNYz7AxDtZQ2zs5idknRlCopOPjf/AIImfsKyft3ftw6X/bVgdQ8C+ADH4h8TvKxK3Dbj9jtWPRvPnjYsOd0MEwP3hX9Lls/mQhufm55xx7cUAfhb/wAE6v2Qv2sv2NZ9P1y6+BfizwzfaVPFpTR6NrujXp1CEhlnfyzcsrRJDHGqvIuCUiCAu7uf2W/Znt9Qg+D9j/aWn+KdLme4upYrbxJqS6hq0UL3EjxieVWYZ2sNqb3KJsVmLK1d59lU7eW+XoM4xSpAsabRnGc8muWjg4UpupB79DSVRyWo+iiiuozCiiigAooooAKKKKACiiigAooooAKKKKACvm7/AIKneHvHfij9kbxFa/D/AEfStY1pV88fbRu+xhFLLKibSThwu4r86oWKgmvpGmvEJD+INAH8+/gXVF+I1nrXg7xf8OY9Q1jwvpml+KJ4LU+Rb6pqTRvKkVqy4jDo0aR+YrurNuyiKPn5uX4n+Ev26NI8L6jGssfhLxJZav4QnguIgJtJ1aeCKa3m2jBJkgikCEgbQuDyzE/ot+31+zsvwO+JC69pFuY/C/iiVpFSHKx2N1tBeMKM4DnMi7R1DjgKM/EvhL4b6R8JdU8WeF5vBl/4m0fx54j0nxHpuq6YkcaaHdxXim6tr5NweO2EYF1BIucSQzKdoPzAHg/j39lbxB+y98P117UvHnhm31O+SGysbjV9NF3dztDCscXkZDPI6xiNceW+1VQnIBx61/wRh/4Jv3H7Zv7UU/i7xDdT6p4N8D3qXuv3t4i/aNXvpEleG3jRvMBw6q8obIEYUDHmAR+MfD9vCvjT/gqLp8/xkudQ1Twevia6stUHmXDPHZotyY7eEW481ULmL5Ihk8ngktX69+I/it41n+GOm6T4RsdP/ZV+DsOLXTLqbT4rnxXrsZ48ux02MH7OXPGTvlbcrhgeCID4A/4LyfCnTv2fP2ytSjtPFF1ptr4y0qz1ODLnUJ7Qqn2Zo5BKZJfJDQmTJZWxMVU4UZ+J7vxMdC+E/irwvqNvZ2euaXLDblbVE8m5SSWJvNV1A3hkO5TyNsqA7WDKv7i6T/wTXv8Axn8LfFC+CPDGnfDW98SWkouPEfjBP7Y8X+JmcEH7RI2fsCSKSGKZk5w0YIzXwX8Ff+Dc742fG/x62m+NI7H4WaBpUkNrdavLJFqM13BB5zKbeCOQh5XDxAszLEvllgX4joYI9u/4Nifif4f0rxBqHgnw7b6hf63qmhy+IPGN5Eh+x2My3IisIXYjG4wO2xQeT5xxkMF/ZSvNf2Tv2YPCP7HXwP0P4e+CdP8AsWh6DCE8yTa1zey4G+4uJAB5kznlnx6AYAAHpVABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAHmf7YsfhFv2a/FcnjqaS08LwWnmXl1HE8klphl2SoE+YsjlWGOuMHgmvzR/aI+A2m+APhPpPiqzVbHxpp8cFzHOk3nabqVqYY3mk8zam6JSrGSP5iI2DoPMjV3/Vn4r/DnSvi98OdY8L65C0+ka7avZ3aq5jbY4xlWHKsOCrDkMAe1fEH7Xn/AASR8bftB6TNd6b8Q9GtdXsbAadYW0mlGK1u4mTbcNIS8gieXO87YyPMyegULpCUUtTOcZNpo/Fu/wD2gP8AhWn7dZ+Juk2WoRto/ij+3LeyhiEt4rq+8QqnzbpPMYx7QrEseAeM/wBKXwZ/Zr0HwDex+JZodQ1rxpewD7Vr2uSC51P5l5jXAEduuCFKQqgO3nc3zH5L/wCCfv8AwQN8C/sxfE+0+JXj7VpviF8SNPvPt+mnD2+k+H5RnaYYd2biVARiafOCA6JGwBH6CRxLFu25+Y7jk96zNB1FFFABRRRQAUUUUAFFFFABRRRQAUUUUAf/2Q==
            Familia Existente:
              value:
                familyId: 1
                familyName: "Arrancador"
                familyCode: "MX1"
                subfamilyName: "Subfamilia 1"
                subfamilyCode: "SF22"
                elementName: "Elemento 1"
                elementCode: "El22"
                modelName: "Modelo 1"
                providerId: 1
                compatibility: "Compatible con todos"
                tradename: "Nombre comercial"
                suggestedPrice: 10000
      required: true
