language: generic
sudo: required
services:
  - docker

deploy:
- provider: elasticbeanstalk
  region: us-east-1
  app: MaxImport
  env: MaxImport-backend-dev
  bucket_name: elasticbeanstalk-us-east-1-047468546016
  bucket_path: MaxImport
  on:
    branch: dev
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY