language: generic
sudo: required
services:
  - docker

deploy:
- provider: elasticbeanstalk
  region: us-east-1
  app: MaxImport-dev
  env: MaxImport-backend
  bucket_name: elasticbeanstalk-us-east-1-047468546016
  bucket_path: MaxImport-dev
  on:
    branch: dev
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY