paths:
  '/auth/login':
    post:
      tags:
        - auth.users
      summary: Login by email and password
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
            examples:
              email:
                value:
                  email: nuevo@correo.com
                  password: 'password'
      responses:
        200:
          description: Success
