paths:
  '/families':
    post:
      tags:
        - families
      summary: Crear una nueva familia
      operationId: addFamily
      responses:
        '201':
          description: Family created
        '400':
          description: Bad request
      requestBody:
        $ref: '#/components/requestBodies/Family'
    get:
      tags:
        - families
      summary: Listar todas las familias
      operationId: listFamily
      responses:
        '200':
          description: Families found
  '/families/{id}':
    get:
      tags:
        - families
      summary: Encontrar familia por Id
      operationId: getFamilyById
      parameters:
        - $ref: '#/components/parameters/paramId'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Resource not found
components:
  requestBodies:
    Family:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
            example:
              name: 'Nueva Familia'
            required:
              - name
      required: true
