paths:
  "/families":
    post:
      tags:
        - inventory.families
      summary: Crear una nueva familia
      operationId: addFamily
      responses:
        "201":
          description: Family created
      requestBody:
        $ref: "#/components/requestBodies/Family"
    get:
      tags:
        - inventory.families
      summary: Listar todas las familias
      operationId: listFamily
      responses:
        "200":
          description: Families found
  "/families/{id}":
    get:
      tags:
        - inventory.families
      summary: Encontrar familia por Id
      operationId: getFamilyById
      parameters:
        - $ref: "#/components/parameters/paramId"
      responses:
        "200":
          description: Successful operation
components:
  requestBodies:
    Family:
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              code:
                type: string
            example:
              name: "Nueva Familia"
              code: "X0X"
            required:
              - name
      required: true
